/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openisl_java_CISLConnect */

#ifndef _Included_com_openisl_java_CISLConnect
#define _Included_com_openisl_java_CISLConnect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Initialize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_Initialize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    New
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_New
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Load
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_Load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Save
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_Save
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SetViewer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SetViewer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SetSessionId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SetSessionId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_Create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Check
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_Check
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Connect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_Connect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    IsTerminated
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_IsTerminated
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_Disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    Free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLConnect_Free
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SetType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SetType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    OpenStore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_OpenStore
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    CloseStore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_CloseStore
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SetMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SetMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    StartListenToExit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_StartListenToExit
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    ListenToExitSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_ListenToExitSession
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SendStopRequest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SendStopRequest
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SendStopSession
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SendStopSession
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SendStopMySession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SendStopMySession
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SetStartTime
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SetStartTime
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    GetStartTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_openisl_java_CISLConnect_GetStartTime
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SetEndTime
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SetEndTime
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    GetEndTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_openisl_java_CISLConnect_GetEndTime
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    SetStepSize
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_SetStepSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    GetStepSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_openisl_java_CISLConnect_GetStepSize
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    GetNbIOs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_GetNbIOs
  (JNIEnv *, jobject);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    GetIOFromId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_GetIOFromId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    NewIO
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLConnect_NewIO
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    PrintError
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLConnect_PrintError
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    PrintWarning
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLConnect_PrintWarning
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_openisl_java_CISLConnect
 * Method:    PrintInfo
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLConnect_PrintInfo
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_openisl_java_CISLData */

#ifndef _Included_com_openisl_java_CISLData
#define _Included_com_openisl_java_CISLData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openisl_java_CISLData
 * Method:    SetConnectionId
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLData_SetConnectionId
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_openisl_java_CISLDoubleData */

#ifndef _Included_com_openisl_java_CISLDoubleData
#define _Included_com_openisl_java_CISLDoubleData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openisl_java_CISLDoubleData
 * Method:    GetDouble
 * Signature: (I[DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_openisl_java_CISLDoubleData_GetDouble
  (JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     com_openisl_java_CISLDoubleData
 * Method:    SetDouble
 * Signature: (IDDI)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLDoubleData_SetDouble
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint);

/*
 * Class:     com_openisl_java_CISLDoubleData
 * Method:    SetDoubleAndStep
 * Signature: (IDDDI)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLDoubleData_SetDoubleAndStep
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_openisl_java_CISLDoubleData
 * Method:    StoreDouble
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLDoubleData_StoreDouble
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     com_openisl_java_CISLDoubleData
 * Method:    InitDouble
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLDoubleData_InitDouble
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_openisl_java_CISLIntData */

#ifndef _Included_com_openisl_java_CISLIntData
#define _Included_com_openisl_java_CISLIntData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openisl_java_CISLIntData
 * Method:    GetInt
 * Signature: (I[DI)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLIntData_GetInt
  (JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     com_openisl_java_CISLIntData
 * Method:    SetInt
 * Signature: (IIDI)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLIntData_SetInt
  (JNIEnv *, jobject, jint, jint, jdouble, jint);

/*
 * Class:     com_openisl_java_CISLIntData
 * Method:    SetIntAndStep
 * Signature: (IIDDI)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLIntData_SetIntAndStep
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jint);

/*
 * Class:     com_openisl_java_CISLIntData
 * Method:    StoreInt
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLIntData_StoreInt
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     com_openisl_java_CISLIntData
 * Method:    InitInteger
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLIntData_InitInteger
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_openisl_java_CISLStringData */

#ifndef _Included_com_openisl_java_CISLStringData
#define _Included_com_openisl_java_CISLStringData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openisl_java_CISLStringData
 * Method:    GetString
 * Signature: (I[DI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_openisl_java_CISLStringData_GetString
  (JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     com_openisl_java_CISLStringData
 * Method:    SetString
 * Signature: (ILjava/lang/String;DI)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLStringData_SetString
  (JNIEnv *, jobject, jint, jstring, jdouble, jint);

/*
 * Class:     com_openisl_java_CISLStringData
 * Method:    SetStringAndStep
 * Signature: (ILjava/lang/String;DDI)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLStringData_SetStringAndStep
  (JNIEnv *, jobject, jint, jstring, jdouble, jdouble, jint);

/*
 * Class:     com_openisl_java_CISLStringData
 * Method:    StoreString
 * Signature: (ILjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_openisl_java_CISLStringData_StoreString
  (JNIEnv *, jobject, jint, jstring, jdouble);

/*
 * Class:     com_openisl_java_CISLStringData
 * Method:    InitString
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_openisl_java_CISLStringData_InitString
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
