#! /bin/bash

ROOT_PATH=`pwd`

OPENISL_PATH="$ROOT_PATH/../.."
export OPENISL_PATH
PYTHON_VENV_PATH="$ROOT_PATH/python"
export PYTHON_VENV_PATH

LD_LIBRARY_PATH="$OPENISL_PATH/bin/x64:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
