/*
 *     Name: isl_errorcodes.h
 *
 *     Description: ISL error codes.
 *
 *     Author: T. Roudier
 *     Copyright (c) 2019-2025 E-Sim Solutions Inc
 *
 *     Distributed under the MIT License.
 * 
 *     --------------------------------------------------------------------------
 * 
 *     Permission is hereby granted, free of charge, to any person obtaining a
 *     copy of this software and associated documentation files (the “Software”),
 *     to deal in the Software without restriction, including without limitation
 *     the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *     and/or sell copies of the Software, and to permit persons to whom the
 *     Software is furnished to do so, subject to the following conditions:
 *
 *     The above copyright notice and this permission notice shall be included in
 *     all copies or substantial portions of the Software.
 *
 *     THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 *     THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *     FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *     DEALINGS IN THE SOFTWARE.
 * 
 *     --------------------------------------------------------------------------
 *
 */

#ifndef _ISL_ERRORCODES_H_
#define _ISL_ERRORCODES_H_

/*
 *     Codes definition
 */

// Error codes
enum {
	APPSETTINGS_INI_LOAD_FAILED = 100,
	APPSETTINGS_INI_NOT_LOADED,
	APPSETTINGS_UNKNOWN_GROUP,
	APPSETTINGS_UNKNOWN_KEY,
	//
	ISLDATATYPE_FREE_ERROR,
	ISLDATATYPE_ALREADY_ALLOCATED,
	ISLDATATYPE_NOFIELD,
	ISLDATATYPE_FIELD_ALREADYEXISTS,
	ISLDATATYPE_NOTVALIDSUBTYPE,
	ISLDATATYPE_SETINITIAL_STRUCTURE,
	ISLDATATYPE_SETINITIAL_NOTALLOCATED,
	ISLDATATYPE_SETINITIAL_FAILED,
	ISLDATATYPE_SETINITIAL_NOELEMENT,
	ISLDATATYPE_SETVALUE_STRUCTURE,
	ISLDATATYPE_SETVALUE_NOTALLOCATED,
	ISLDATATYPE_SETVALUE_FAILED,
	//
	ISLVARIABLE_NO_PARENT,
	ISLVARIABLE_EMPTY_ID,
	ISLVARIABLE_VAR_EXISTS,
	ISLVARIABLE_TYPE_ALREADYSET,
	ISLVARIABLE_TYPE_NOTVALID,
	ISLVARIABLE_CHECK_NOIDNONAME,
	ISLVARIABLE_CHECK_NOCAUSALITY,
	ISLVARIABLE_CHECK_NODATATYPE,
	ISLVARIABLE_CHECK_INVALIDTYPE,
	//
	ISLDATA_NO_CONNECTOR_LINKED,
	ISLDATA_WRONG_SHMSIZE,
	ISLDATA_FAILED_CREATESHM,
	ISLDATA_FAILED_CONNECTSHM,
	ISLDATA_NOVALIDSHMSPACE,
	ISLDATA_FAILED_INITSHM,
	//
	ISLSHMDATA_NO_CONNECTOR_LINKED,
	ISLSHMDATA_NOT_ALLOCATED,
	ISLSHMDATA_WRONG_STRUCTURE,
	//
	ISLCONNECT_NEW_NAMEREQUIRED,
	ISLCONNECT_LOAD_FILENOTEXIST,
	ISLCONNECT_LOAD_LOADFAILED,
	ISLCONNECT_LOAD_PARSEFAILED,
	ISLCONNECT_LOAD_FAILED_TOGETVARS,
	ISLCONNECT_LOAD_NOVARS,
	ISLCONNECT_LOAD_IMPORTFAILED,
	ISLCONNECT_CHECK_NONAME,
	ISLCONNECT_CHECK_NEGSTARTTIME,
	ISLCONNECT_CHECK_NEGENDTIME,
	ISLCONNECT_CHECK_NEGSTEPSIZE,
	ISLCONNECT_CHECK_ENDBEFORESTART,
	ISLCONNECT_CHECK_WRONGSTEPSIZE,
	ISLCONNECT_CHECK_NOIOS,
	ISLCONNECT_CHECK_IOFAILED,
	ISLCONNECT_SAVE_CHECKFAILED,
	ISLCONNECT_SAVE_FAILED,
	ISLCONNECT_SETSESSION_WRONGFORMAT,
	ISLCONNECT_NEWIO_NOIDNONAME,
	ISLCONNECT_NEWIO_IOALREADYEXIST,
	ISLCONNECT_ADDIO_IOALREADYEXIST,
	ISLCONNNECT_ADDIO_NODATA,
	ISLCONNNECT_REMOVEIO_NODATA,
	ISLCONNECT_GETIO_NOIOS,
	ISLCONNECT_GETIO_NOID,
	ISLCONNECT_GETIN_NOID,
	ISLCONNECT_GETOUT_NOID,
	ISLCONNECT_CREATE_ALREADYRUNNING,
	ISLCONNECT_CREATE_CHECKFAILED,
	ISLCONNECT_CREATE_SHMEXIST,
	ISLCONNECT_CREATE_NOVALIDSESSION,
	ISLCONNECT_CREATE_WRONGSHMSIZE,
	ISLCONNECT_CREATE_CREATESHMFAILED,
	ISLCONNECT_CREATE_CONNECTSHMFAILED,
	ISLCONNECT_CREATE_NOVALIDSHMSPACE,
	ISLCONNECT_CREATE_INITSHMFAILED,
	ISLCONNECT_CREATE_DATACONNECTFAILED,
	ISLCONNECT_CREATE_ISLSIMSFAILED,
	ISLCONNECT_CONNECT_NOTREADY,
	ISLCONNECT_CONNECT_FAILEDINPUT,
	ISLCONNECT_CONNECTVIEWER_FAILEDIO,
	ISLCONNECT_DISCONNECT_NOTCONNECTED,
	ISLCONNECT_DISCONNECT_FAILEDIO,
	ISLCONNECT_DISCONNECTVIEWER_FAILEDIO,
	//
	ISLSIMS_CONNECT_FAILEDTOATTACHSHM,
	ISLSIMS_CONNECT_FAILEDTOCREATESHM,
	ISLSIMS_CONNECT_FAILEDTOGETDATA
};

// Warning codes
enum {
	ISLDATATYPE_POSITIVE_SIZE = 300,
	ISLDATATYPE_STRUCTURE_NO_ARRAY,
	ISLDATATYPE_NOINITIAL_FROMSTR,
	ISLDATATYPE_NOINITIAL_TOSTR,
	ISLDATATYPE_SETINITIAL_NOVAL,
	//
	ISLVARIABLE_CHECK_NOID,
	ISLVARIABLE_CHECK_NONAME,
	ISLVARIABLE_CHECK_ALLOCATION,
	ISLVARIABLE_CHECK_NOTCONNECTED,
	ISLVARIABLE_CHECK_ZEROSTEPSIZE,
	ISLVARIABLE_CHECK_WRONGSTEPSIZE,
	ISLVARIABLE_CHECK_ZEROSYNCTIMEOUT,
	//
	ISLDATA_ALREADY_CONNECTED,
	ISLDATA_NO_CONNECTID,
	//
	ISLSHMDATA_NO_INITIAL_VALUE,
	//
	ISLEXITTHREAD_STOP_RECEIVED,
	ISLEXITTHREAD_EXITINGAPP,
	//
	ISLCONNECT_NEW_ALREADYCONNNECTED,
	ISLCONNECT_LOAD_ALREADYCONNNECTED,
	ISLCONNECT_CHECK_ALREADYCONNNECTED,
	ISLCONNECT_CHECK_ALREADYCHECKED,
	ISLCONNECT_CHECK_NOMODELID,
	ISLCONNECT_CHECK_NOTYPE,
	ISLCONNECT_CHECK_NOSESSIONID,
	ISLCONNECT_CHECK_NEGCONNECTTIMEOUT,
	ISLCONNECT_CHECK_NONZEROSTARTTIME,
	ISLCONNECT_CHECK_WRONGSTEPTOLERANCE,
	ISLCONNECT_SAVE_NOFILENAME,
	ISLCONNECT_SAVE_NOTCHECKED,
	ISLCONNECT_CANNOTMODIFY_AFTERCONNECT,
	ISLCONNECT_REMOVEIO_NOTFOUND,
	ISLCONNECT_GETIN_NOTCHECKED,
	ISLCONNECT_GETOUT_NOTCHECKED,
	ISLCONNECT_CREATE_NOTCHECKED
};

// Info codes
enum {
	ISLVARIABLE_CHECK_INFO = 500,
	//
	ISLDATA_CONNECT_CREATESHM,
	ISLDATA_CONNECT_CONNECTSHM,
	ISLDATA_CONNECT_CONNECTED,
	ISLDATA_DETACHINGSHM,
	//
	ISLEXITTHREAD_SETTERMINATED,
	//
	ISLCONNECT_UNLOADING_API,
	ISLCONNECT_CREATING_NEWCONFIG,
	ISLCONNECT_NEWMODEL_UUID,
	ISLCONNECT_NEWMODEL_TYPE,
	ISLCONNECT_NEWMODEL_TIMES,
	ISLCONNECT_NEWMODEL_CREATED,
	ISLCONNECT_LOADING_FILE,
	ISLCONNECT_PARSING_FILE,
	ISLCONNECT_LOAD_COMPLETED,
	ISLCONNECT_CHECK_RUNNING,
	ISLCONNECT_CHECK_COMPLETED,
	ISLCONNECT_CHECK_MODELINFO,
	ISLCONNECT_CHECK_COSIMINFO,
	ISLCONNECT_CHECK_EVENTMODE,
	ISLCONNECT_GETID_NEWUUID,
	ISLCONNECT_NEWIO_ADDED,
	ISLCONNECT_ADDIO_ADDED,
	ISLCONNECT_REMOVEIO_REMOVED,
	ISLCONNECT_VIEWER_BEFORECONNNECT,
	ISLCONNECT_CREATE_CREATESHM,
	ISLCONNECT_CREATE_VIEWERMODE,
	ISLCONNECT_CREATE_CONNECTSHM,
	ISLCONNECT_CREATE_CREATED,
	ISLCONNECT_CREATE_ISLSIMADD,
	ISLCONNECT_CREATE_ISGLOBALIPC,
	ISLCONNECT_CREATE_ISLCOMPATIBLE,
	ISLCONNECT_CONNECT_CONNECTED,
	ISLCONNECT_CONNECTVIEWER_CONNECTED,
	ISLCONNECT_DISCONNECT_TIMER,
	ISLCONNECT_DISCONNECT_DETACHSHM,
	ISLCONNECT_DISCONNECT_DISCONNECTED,
	ISLCONNECT_DISCONNECT_ISLSIMSREMOVE,
	ISLCONNECT_DISCONNECTVIEWER_DISCONNECTED,
	ISLCONNECT_SAVE_SAVING,
	ISLCONNECT_SAVE_SAVED,
	//
	ISLSIMS_CONNECT_CONNECTED,
	ISLSIMS_CONNECT_CREATED
};

// Debug codes
enum {
	ISLSHMDATA_DEBUG = 900,
	ISLDATA_DEBUG
};

#endif // _ISL_ERRORCODES_H_
